- name: Config Setup
  hosts: localhost
  become: yes
  tasks:
  - name: Add OBS Studio repo
    apt_repository:
      repo: "ppa:obsproject/obs-studio"
      state: present

  - name: Install Packages with apt
    apt:
      pkg:
        - redshift
        - vagrant
        - libimage-exiftool-perl
        - perl-doc
        - virtualbox
        - vlc
        - wireshark
        - nmap
        - obs-studio
        - openvpn
        - telnet
        - pidgin
        - tmux
        - vim
        - wget
        - gnome-shell-extensions
        - gnome-shell-extension-manager
        - gir1.2-gda-5.0
        - gir1.2-gsound-1.0
        - keepassxc
        - thunderbird

      state: latest
      update_cache: true
  - name: Install Snaps
    community.general.snap:
      name:
        - brave
        - codium
        - slack
        - metasploit-framework
        - spotify
        - zotero-snap
        - docker
